export const PERMISSIONS = {
    // Platform Super Admin
    PLATFORM_MANAGE_GYMS: 'platform:manage_gyms',
    PLATFORM_MANAGE_PLANS: 'platform:manage_plans',
    PLATFORM_VIEW_METRICS: 'platform:view_metrics',
    // Gym & Branch Settings
    GYM_MANAGE_SETTINGS: 'gym:manage_settings',
    GYM_MANAGE_BRANCHES: 'gym:manage_branches',
    GYM_MANAGE_STAFF: 'gym:manage_staff',
    // Member Management
    MEMBER_VIEW: 'member:view',
    MEMBER_CREATE_EDIT: 'member:create_edit',
    MEMBER_DELETE: 'member:delete',
    // Membership & Plans
    MEMBERSHIP_PLAN_MANAGE: 'membership_plan:manage',
    MEMBERSHIP_ASSIGN_RENEW: 'membership:assign_renew',
    // Payments
    PAYMENT_VIEW: 'payment:view',
    PAYMENT_RECORD: 'payment:record',
    PAYMENT_MANAGE: 'payment:manage',
    // Attendance
    ATTENDANCE_VIEW: 'attendance:view',
    ATTENDANCE_MARK: 'attendance:mark',
    // Analytics & Reports
    REPORTS_VIEW: 'reports:view',
    AUDIT_LOGS_VIEW: 'audit_logs:view',
};
export const ROLE_PERMISSIONS = {
    SUPER_ADMIN: [
        PERMISSIONS.PLATFORM_MANAGE_GYMS,
        PERMISSIONS.PLATFORM_MANAGE_PLANS,
        PERMISSIONS.PLATFORM_VIEW_METRICS,
        PERMISSIONS.GYM_MANAGE_SETTINGS,
        PERMISSIONS.GYM_MANAGE_BRANCHES,
        PERMISSIONS.GYM_MANAGE_STAFF,
        PERMISSIONS.MEMBER_VIEW,
        PERMISSIONS.MEMBER_CREATE_EDIT,
        PERMISSIONS.MEMBER_DELETE,
        PERMISSIONS.MEMBERSHIP_PLAN_MANAGE,
        PERMISSIONS.MEMBERSHIP_ASSIGN_RENEW,
        PERMISSIONS.PAYMENT_VIEW,
        PERMISSIONS.PAYMENT_RECORD,
        PERMISSIONS.PAYMENT_MANAGE,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_MARK,
        PERMISSIONS.REPORTS_VIEW,
        PERMISSIONS.AUDIT_LOGS_VIEW,
    ],
    GYM_OWNER: [
        PERMISSIONS.GYM_MANAGE_SETTINGS,
        PERMISSIONS.GYM_MANAGE_BRANCHES,
        PERMISSIONS.GYM_MANAGE_STAFF,
        PERMISSIONS.MEMBER_VIEW,
        PERMISSIONS.MEMBER_CREATE_EDIT,
        PERMISSIONS.MEMBER_DELETE,
        PERMISSIONS.MEMBERSHIP_PLAN_MANAGE,
        PERMISSIONS.MEMBERSHIP_ASSIGN_RENEW,
        PERMISSIONS.PAYMENT_VIEW,
        PERMISSIONS.PAYMENT_RECORD,
        PERMISSIONS.PAYMENT_MANAGE,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_MARK,
        PERMISSIONS.REPORTS_VIEW,
        PERMISSIONS.AUDIT_LOGS_VIEW,
    ],
    MANAGER: [
        PERMISSIONS.GYM_MANAGE_STAFF,
        PERMISSIONS.MEMBER_VIEW,
        PERMISSIONS.MEMBER_CREATE_EDIT,
        PERMISSIONS.MEMBERSHIP_PLAN_MANAGE,
        PERMISSIONS.MEMBERSHIP_ASSIGN_RENEW,
        PERMISSIONS.PAYMENT_VIEW,
        PERMISSIONS.PAYMENT_RECORD,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_MARK,
        PERMISSIONS.REPORTS_VIEW,
    ],
    STAFF: [
        PERMISSIONS.MEMBER_VIEW,
        PERMISSIONS.MEMBER_CREATE_EDIT,
        PERMISSIONS.MEMBERSHIP_ASSIGN_RENEW,
        PERMISSIONS.PAYMENT_VIEW,
        PERMISSIONS.PAYMENT_RECORD,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_MARK,
    ],
    TRAINER: [
        PERMISSIONS.MEMBER_VIEW,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_MARK,
    ],
};
export function hasPermission(role, permission) {
    return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
